version: 2
jobs:
  build_and_test:
    working_directory: ~/babel-cli
    docker:
      - image: node:10-jessie
    steps:
      - checkout
      - restore_cache:
          name: Restore Packages Cache
          keys:
            - packages-{{ .Branch }}-{{ checksum "yarn.json" }}
            - packages-{{ .Branch }}
            - packages-master
      - run:
          name: Packager Version
          command: npm version
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Packages Cache
          key: packages-{{ .Branch }}-{{ checksum "yarn.json" }}
          paths:
            - node_modules/
      - run:
          name: Lint sources
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
